name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hellow_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola mundo!"